### ISSUE TITLE
Synchronization long polling notification feature

### ISSUE THREAD

**Issue by noobj** [noobj/swim-go-serverless-crawler#4]
### Description:

Needs a mechanism to notify the client when the handler finishes the synchronization.
So basically the front-end will long polling the sync notifier with the returned task id until the task has been done.

### Workflow:
<img src="https://mermaid.ink/img/pako:eNp1U8uu2jAQ_RXLG0Di0SQQIItKXCgU6baXQrup2Jh4klgEO7WdSynw77UdXrePyAt7cs7MOR7PEceCAo5wkot9nBGp0fNyzZH5RvV6fZwz4LrRaKBW6_1pdeAxkvCjBKVPyJ6WdRdbQgzsFWSjYq6-rBx-IQqUEU5zuLMmFeOjC18JEwf_VlCiAWmitkhpokuFtEC1ieBQM8QDJztxKWBLWw6aT48zIVJT4WVU6gy9bM8VZD6tJJdxDEqhllGgS8mr7IyeRv-FOaFIWZUW7Fx_NZs3hClhOVCHp0xCrK1UYhUUJAXHGT9VVsckzzck3jbu2sdPLsm_Jd0BbytfT4465wrkg8rrhdUWwCnjae30533dqItSZX-1xbTs0nWHeRY8RYXIc5MK7ZmxdRWJZpWrz0KzhN06OHvsoCNw2CPzdiQDhfYZXGxS08wTujitJDrmOIN4--jEFMJNvAO5I4ya93m0lDXWGexgjSOzpURu13jNzwZnbl5YWTjSsoQmLp2QCSOpJDscJSRXt-gHyrSQt2AuCAVzPGJ9KOwkpExpkzIWPGGpjZcyN-FM60JFnY793U6Nw3LTjsWuoxi1Y5O9DsNO6IcD4gcQ9gPSCwIab7zhIPG7XkL77zyf4PO5iQvCbdafOGp1g7bf8_3ecOiH3X7Qa-IDjnr9tu8PuoFd_TD0DOWXEMaF1zagYTgY9rtBYEp5gyYGZ-ZTNcNulF2B747gHJ5_A_a2QT0">

### To-Dos:

Sync Receiver
- [x] Insert task id to Dynamo and return it to the client

Sync Callback
- [x] Extract the identical part with the receiver and make it a general function

Sync Checker
- [x] Keep checking the task status and return to the polling client when status updated
Referencing the article: https://kerkour.com/go-http-long-polling#/
The status could be "Done, Pending, Failed"

Sync Handler
- [x] Update task status when finish work
Could be failed or done
